project_id = "jiwvcamqrzzobidjbezu"

[functions.create-checkout]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-cart-recovery]
verify_jwt = false

[functions.auto-cart-recovery]
verify_jwt = false
