project_id = "jiwvcamqrzzobidjbezu"

[functions.create-checkout]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-cart-recovery]
verify_jwt = false

[functions.auto-cart-recovery]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.send-refund-email]
verify_jwt = false

[functions.process-refund]
verify_jwt = false
